### ISSUE TITLE
pull about the redundant import in templates

### ISSUE THREAD

**Issue by gspia** [snapframework/snap-templates#15]
Hi
I tested the pull #13 by making the change by hand to the code. Monoids are not used meaning that the default-template will compile and install with cabal even if there is 'import Data.Monoid' in the source.

Thus, could you please decide whether to remove that line or leave it. I'll guess there will be good arguments for both actions. After that the pull-request could be closed (and this issue, too).

It seemed that the pull request has already the relevant code changes. Is it easy to merge that to the head branch? I'm asking this, because I could propose some minor additions or changes but I'm not sure what is an appropriate nor convenient way. (Late add: email had a suggestion to make commits and to make pull-requests, I'll try that.) 

And where to discuss proposals? (E.g. I tried the forthcoming 1.0 version with a recent React.js -library and got some examples to work. What would you think about a new template 'snap init react' that has a couple of examples with source links to the official react-sources? Maybe later after 1.0 release?)

**Comment by mightybyte** [comment]
Thanks again for all your testing.  I merged the other pull request.  The best way to propose changes is to fork this repository and commit whatever changes you have in mind to your fork.  Then issue a pull request.  That will package all your changes up in a way that's easy for us to look at and comment on.

As far as your suggestion for a react project template, I don't think it would be appropriate to include it in this repository because it will increase our maintenance burden and I don't know if any of the core Snap developers uses React.js enough to make good decisions.  But there is nothing stopping you from publishing your react template anyway!  You could leave it in your fork of this repository, or you could make a standalone repo just for that.  I think that it's great to have a healthy community creating and publishing whatever tools they have that make their life easier.  Then you can blog about them, post them to the Haskell reddit, etc and the community benefits.

**Comment by gspia** [comment]
Hi & thanks,
Ok, I'll try to do that. I was/am planning to do a short tutorial using
react and snap-framework together, even though it is not that Haskell-way
that it possibly could be by using some other technique.
br, gspia

2016-06-21 15:20 GMT+03:00 Doug Beardsley <notifications@github.com>:

> Thanks again for all your testing. I merged the other pull request. The
> best way to propose changes is to fork this repository and commit whatever
> changes you have in mind to your fork. Then issue a pull request. That will
> package all your changes up in a way that's easy for us to look at and
> comment on.
>
> As far as your suggestion for a react project template, I don't think it
> would be appropriate to include it in this repository because it will
> increase our maintenance burden and I don't know if any of the core Snap
> developers uses React.js enough to make good decisions. But there is
> nothing stopping you from publishing your react template anyway! You could
> leave it in your fork of this repository, or you could make a standalone
> repo just for that. I think that it's great to have a healthy community
> creating and publishing whatever tools they have that make their life
> easier. Then you can blog about them, post them to the Haskell reddit, etc
> and the community benefits.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/snapframework/snap-templates/issues/15#issuecomment-227422839>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADKr2PLXxh7htXlqnnbgd5DRjrMCHZIFks5qN9cWgaJpZM4I6Zt->
> .
>



-- 
br,
Isto
